#!/bin/bash
# Copyright © 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

# Generate Dockerfile from config.rc for building worker container image
# Usage: create_dockerfile.sh <workdir>

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TUNE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

. "$TUNE_ROOT/lib/config_load.sh"

WORKDIR="$1"

if [ -z "$WORKDIR" ]; then
  echo "Usage: $0 <workdir>" >&2
  exit 1
fi

load_config "$WORKDIR"

if [ -z "$CELERY_WORKER_IMAGE_BASE" ]; then
  echo "Error: CELERY_WORKER_IMAGE_BASE not set in config.rc" >&2
  exit 1
fi

if [ -z "$CELERY_WORKER_PYTHON" ]; then
  echo "Error: CELERY_WORKER_PYTHON not set in config.rc" >&2
  exit 1
fi

# Create output directory
IMAGE_BUILD_DIR="$WORKDIR/image.build"
mkdir -p "$IMAGE_BUILD_DIR"

# Generate Dockerfile
cat > "$IMAGE_BUILD_DIR/Dockerfile" <<EOF
# Auto-generated by .tune/single/create_dockerfile.sh
# WARNING: This file will be overwritten when prepwkdir is run.
#          Do not manually edit. Customize via config.rc or image.scripts/ instead.
FROM ${CELERY_WORKER_IMAGE_BASE}

COPY config.rc /config.rc
# Copy scripts
COPY image.scripts /image.scripts

# Create venv if CELERY_WORKER_PYTHON doesn't exist and install wheels
RUN if [ ! -f ${CELERY_WORKER_PYTHON} ]; then \\
      python3 -m venv \$(dirname \$(dirname ${CELERY_WORKER_PYTHON})); \\
      ${CELERY_WORKER_PYTHON} -m pip install /torch-*.whl /triton-*.whl; \\
    fi

# Install requirements-tuning.txt
COPY aotriton.src/requirements*.txt /tmp/
RUN ${CELERY_WORKER_PYTHON} -m pip install -r /tmp/requirements-tuning.txt && \\
    ${CELERY_WORKER_PYTHON} -m pip install -r /tmp/requirements-dev.txt && \\
    rm /tmp/requirements*.txt

# Run all scripts matching pattern: NN-*.sh
RUN for script in /image.scripts/[0-9][0-9]-*.sh; do \\
      if [ -f "\$script" ]; then \\
        echo "Running \$script"; \\
        bash "\$script"; \\
      fi \\
    done

# Cleanup
RUN rm -rf /image.scripts
RUN rm -f /config.rc
EOF

echo "Generated Dockerfile at: $IMAGE_BUILD_DIR/Dockerfile"
