#!/usr/bin/env
# Copyright © 2025 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

if [ -z "$BASH_VERSION" ]; then
  echo "This script requires Bash. Please run it with 'bash script_name.sh' or ensure /bin/sh points to /bin/bash." >&2
  exit 1
fi
SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"

if [ ! -t 0 ]; then
  echo "This script requires TTY inputs for interactive operations" >&2
  exit 1
fi

if [ "$#" -ne 1 ]; then
  echo 'Missing arguments. Usage: create-project-directory.sh <dir>' >&2
  exit 1
fi
dir="$1"

mkdir "$dir"

if [ ! -d "$dir" ]; then
  echo 'Cannot create directory $dir' >&2
  exit 1
fi
rcfile="$dir/config.rc"

echo "Enter secret for services."
echo "This secret will be the common passwords for all services like rabbitmq/postgresql."
echo "random passwords will be used if empty"
read -p "Secret: " secret
if [[ -z "$secret" ]]; then
  secret=$(head -c 16 /dev/urandom | xxd -p)
  echo "Using secret $secret from /dev/urandom"
fi
read -p "Docker Image to Run Worker: " image
read -e -p "Docker Volume Name for PostgreSQL Database: " -i "aotriton_pgdata"  pgvolume
while true; do
	read -r -p "Docker Container Suffix (only allows a-zA-Z0-9_-): " suffix
  # Check if the input contains ONLY a-z, A-Z, and 0-9
  if [[ "$suffix" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    echo "Valid input received: $suffix"
    break # Exit the loop if validation passes
  else
    echo "Invalid input. Only a-zA-Z0-9_- characters are allowed."
  fi
done

echo ""
echo "Python configuration for worker:"
echo "1) Use existing python (provide path, e.g., /opt/venv/bin/python)"
echo "2) Create venv at /wkdir/venv (will install torch and triton wheels)"
echo "For other configurations, you can edit config.rc and inpod.create_venv.sh afterwards"
read -p "Choose option [1/2]: " python_option

if [[ "$python_option" == "2" ]]; then
  worker_python="/wkdir/venv/bin/python"

  # Create inpod.create_venv.sh script
  cat << 'VENV_SCRIPT' > "$dir/inpod.create_venv.sh"
#!/bin/bash
# Auto-generated by create-project-directory.sh

if [ -f /wkdir/venv/bin/python ]; then
  echo "venv already exists, skipping creation"
  exit 0
fi
python3 -m venv /wkdir/venv
/wkdir/venv/bin/pip install /torch-*.whl /triton-*.whl
if [ -f /wkdir/aotriton.src/requirements-tuning.txt ]; then
  /wkdir/venv/bin/pip install -r /wkdir/aotriton.src/requirements-tuning.txt
fi
VENV_SCRIPT
else
  if [[ "$python_option" != "1" ]]; then
    echo "Invalid option. Defaulting to option 1."
  fi
  read -p "Python path: " -i "/opt/venv/bin/python" python_path
  worker_python="$python_path"

  # Create inpod.create_venv.sh script for existing python
  cat << VENV_SCRIPT > "$dir/inpod.create_venv.sh"
#!/bin/bash
# Auto-generated by create-project-directory.sh

if [ -f /wkdir/aotriton.src/requirements-tuning.txt ]; then
  $worker_python -m pip install -r /wkdir/aotriton.src/requirements-tuning.txt
fi
VENV_SCRIPT
fi
chmod +x "$dir/inpod.create_venv.sh"

cat << EOF > "$rcfile"
RABBITMQ_DEFAULT_USER=aotriton
RABBITMQ_DEFAULT_PASS=$secret
RABBITMQ_NODE_PORT=5672
POSTGRES_USER=aotriton
POSTGRES_PASSWORD=$secret
POSTGRES_PORT=5432
POSTGRES_DOCKER_IMAGE=postgres:17.6
POSTGRES_DOCKER_VOLUME=$pgvolume
CONTAINER_SUFFIX=$suffix
CELERY_SERVICE_HOST=$(hostname -f)
CELERY_WORKER_IMAGE=$image
CELERY_WORKER_PYTHON=$worker_python
EOF
