#!/bin/bash
# Copyright © 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

if [ -z "$BASH_VERSION" ]; then
  echo "This script requires Bash. Please run it with 'bash script_name.sh' or ensure /bin/sh points to /bin/bash." >&2
  exit 1
fi

if [ "$#" -ne 1 ]; then
  cat >&2 <<EOF
Usage: $0 <workdir>

Generate Dockerfile from config.rc for building worker container image.

Arguments:
  <workdir>  Project working directory

Output:
  <workdir>/image.build/Dockerfile
EOF
  exit 1
fi

SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
AOTRITON_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
WORKDIR="$1"
CONFIG_RC="$WORKDIR/config.rc"

# Validate
if [ ! -d "$WORKDIR" ] || [ ! -f "$CONFIG_RC" ]; then
  echo "Error: Invalid workdir or config.rc not found" >&2
  exit 1
fi

# Source config
. "$CONFIG_RC"

if [ -z "$CELERY_WORKER_IMAGE_BASE" ]; then
  echo "Error: CELERY_WORKER_IMAGE_BASE not set in config.rc" >&2
  exit 1
fi

if [ -z "$CELERY_WORKER_PYTHON" ]; then
  echo "Error: CELERY_WORKER_PYTHON not set in config.rc" >&2
  exit 1
fi

# Create output directory
IMAGE_BUILD_DIR="$WORKDIR/image.build"
mkdir -p "$IMAGE_BUILD_DIR"

# Generate Dockerfile
cat > "$IMAGE_BUILD_DIR/Dockerfile" <<EOF
# Auto-generated by create-Dockerfile.sh
# WARNING: This file will be overwritten when prepare-workdir.sh is run.
#          Do not manually edit. Customize via config.rc or image.scripts/ instead.
FROM ${CELERY_WORKER_IMAGE_BASE}

# Copy scripts
COPY image.scripts /image.scripts

# Create venv if CELERY_WORKER_PYTHON doesn't exist and install wheels
RUN if [ ! -f ${CELERY_WORKER_PYTHON} ]; then \\
      python3 -m venv \$(dirname \$(dirname ${CELERY_WORKER_PYTHON})); \\
      ${CELERY_WORKER_PYTHON} -m pip install /torch-*.whl /triton-*.whl; \\
    fi

# Install requirements-tuning.txt
COPY aotriton.src/requirements-tuning.txt /tmp/requirements-tuning.txt
RUN ${CELERY_WORKER_PYTHON} -m pip install -r /tmp/requirements-tuning.txt && \\
    rm /tmp/requirements-tuning.txt

# Run all scripts matching pattern: NN-*.sh
RUN for script in /image.scripts/[0-9][0-9]-*.sh; do \\
      if [ -f "\$script" ]; then \\
        echo "Running \$script"; \\
        bash "\$script"; \\
      fi \\
    done

# Cleanup
RUN rm -rf /image.scripts
EOF

echo "Generated Dockerfile at: $IMAGE_BUILD_DIR/Dockerfile"
echo ""
echo "To build the image, run:"
echo "  docker build -f $IMAGE_BUILD_DIR/Dockerfile -t ${CELERY_WORKER_IMAGE} $WORKDIR"
